### ISSUE TITLE
No module names soundfile

### ISSUE THREAD

**Issue by theonlygusti** [facundoq/speech_synthesis#1]
```
Traceback (most recent call last):
  File "tts.py", line 4, in <module>
    import diphone_db
  File "/Users/theonlygusti/Documents/Subjects/Computing/ExtendedEssay/speech_synthesis/diphone_db.py", line 1, in <module>
    import soundfile as sf
ImportError: No module named soundfile
```

I installed pysoundfile seemingly without trouble:

```
$ sudo pip install pysoundfile
The directory '/Users/theonlygusti/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/theonlygusti/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pysoundfile
  Downloading PySoundFile-0.9.0.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-macosx_10_5_x86_64.macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl (573kB)
    100% |████████████████████████████████| 573kB 430kB/s
Requirement already satisfied: cffi>=0.6 in /Library/Python/2.7/site-packages (from pysoundfile)
Requirement already satisfied: pycparser in /Library/Python/2.7/site-packages (from cffi>=0.6->pysoundfile)
Installing collected packages: pysoundfile
Successfully installed pysoundfile-0.9.0.post1
```

**Comment by facundoq** [comment]
@theonlygusti, I've no idea why this isn't working for you, since this is unrelated to this code's repo (you are just importing a library).

You can probably file an issue on the PySoundFile project and get help from them.
